### ISSUE TITLE
Improve error reporting while adding wrong step proc

### ISSUE THREAD

**Issue by iJackUA** [trailblazer/trailblazer-operation#15]
Very common and simple usecase to define step in operation
`step Contract::Build()`
if you make a typo and write 
`step Contract::Build`
it still syntactically correct, as `self.Build()` exists and `Build` module exists.
But of course you'll get an error
`NoMethodError: undefined method 'call' for nil:NilClass' in
.../pipetree-0.1.1/lib/pipetree/railway.rb:77:in 'call'`

and it is completely not clear initially what is the reason if this failure.

I am no sure at which level it is better to catch - in Operation or Railway gem.

**Comment by apotonick** [comment]
This should be caught on operation level as `step` is TRB-specific. The pipetree gem will get replaced with the newer, way simpler `circuit` gem.

**Comment by apotonick** [comment]
BTW, what about our plans to meet up in Kharkiv? :beers:

**Comment by iJackUA** [comment]
Aha, I see `circuit` gem, looking forward to seeing the examples of its usage.
But if to go back to the initial issue. As `step` accept wide variety of inputs: symbol, lambda etc. And it seems hard to distinguish is this input correct or not at the very beginning (as Ruby has no Interfaces or a special type like `Callable` in PHP), so maybe just to use a "respond_to" check?  (I know how much you hate it :D)

**Comment by iJackUA** [comment]
As for the meetup, I'll better contact you in Gitter or Twitter.

**Comment by panSarin** [comment]
I close the issue since it have 3 years. But if you want to discuss ways of checking if input is correct please join our zulipchat https://trailblazer.zulipchat.com/join/od4yhihn6tra3ix39u4gks72/  and discuss possible approaches there. Also, documentation about 2.1 is there: https://2019.trailblazer.to/2.1/docs/trailblazer.html already and will be updated with few more sections during next few days. If it misses something, let's discuss it so we can add it on documentation page.
